backend:
  name: github
  repo: bianic8-del/beatriz-carvalho-advocacia
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Artigos"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "excerpt", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
